### ISSUE TITLE
Trailing backslash is not handled

### ISSUE THREAD

**Issue by jludev1** [mattdsteele/java-properties#11]
A property value can span several lines if each line is terminated by a backslash (‘\’) character. For example:

targetCities=\
        Detroit,\
        Chicago,\
        Los Angeles

This is equivalent to targetCities=Detroit,Chicago,Los Angeles (white space at the beginning of lines is ignored).
http://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html

**Comment by mattdsteele** [comment]
Interesting! I was unaware of that.

Fixed and published as version `0.2.4`.

**Comment by jludev1** [comment]
great, thanks!
