### ISSUE TITLE
utf8 file with \uxxxx car are not read correctly

### ISSUE THREAD

**Issue by jmcollin78** [mattdsteele/java-properties#15]
Hi Matt,

I'm not sure it is a problem related to the module but I've got a problem I cannot correct.
Here a very simple test:
<pre>
-- utf.properties --
utf8.string = \u2601 a string with accent : crédits seront très bientôt épuisés
</pre>
The test failing now:
<pre>
'utf8 strings' : function(test) {
      test.expect(2);
      var myFile = new PropertiesFile('test/fixtures/utf8.properties');
      var str = myFile.get('utf8.string');
      test.equal(str, '\u2601 a string with accent : crédits seront très bientôt épuisés');
      test.equal(str.charAt(0),String.fromCharCode(0x2601));
      test.done();
  }
</pre>
The result of the first test is the following:
<pre>
AssertionError: '\\u2601 a string with accent : crédits seront très bientôt épuisés' == '☁ a string with accent : crédits seront très bientôt épuisés'
</pre>
And the result of the second test:
<pre>
AssertionError: '\\' == '☁'
    at Object.equal (d:\Projets\Clouderial\nodeProjects\java-properties\node_modules\gulp-nodeunit\node_modules\nodeunit\lib\types.js:83:39)
    at Object.exports.properties.utf8 strings (d:\Projets\Clouderial\nodeProjects\java-properties\test\properties_test.js:301:12)
</pre>

The '\u2601' (which is a cloud symbol) is transformed in \\u2601 when reading the file which breaks the utf8 char.

I search on option in fs.readXxxx without success.

Any clues would be greatly appreciated.

**Comment by jmcollin78** [comment]
OK i've got it.
\uxxxx are Unicode caracters. They can be decoded with this piece of code (in line 35 of your properties.js:
<code>
            // the key does not exists
            this.objs[key] = unescape(JSON.parse('"' + value.replace('"', '\\"') + '"'));
</code>
I will do a PR if you agree with that hack.

JM.

**Comment by jmcollin78** [comment]
https://github.com/mattdsteele/java-properties/pull/16

**Comment by mattdsteele** [comment]
Merged into `0.2.8`.
