### ISSUE TITLE
Only '=' is supported as separator

### ISSUE THREAD

**Issue by komu** [mattdsteele/java-properties#20]
The code only supports using `=` for separator, but `:` and whitespace are also valid separators in property files. Furthermore, the separator characters may be escaped in which case they can be used in keys.

See [Properties.load()](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-) for details.

**Comment by mattdsteele** [comment]
`1.0.2` provides support for `:`
